### PR TITLE
Switched from npm to yarn

### PR DESCRIPTION
**Pull request by okonomi**
# Overview

I switched from npm to yarn.

- Add `yarn.lock`
- Remove `npm-shrinkwrap.json`
- Modify CircleCI configuration
- Update README

# Motivation

I tried and tried to version up of React.
I edited the package.json, run `npm install`, returned version, re-run ` npm install`, and added and deleted some packages a few times.
Then, old versions of packages sometimes remain in `node_modules`.

Also, it was happening that `npm shrinkwrap` failed for some reason.
If yarn, that does not happen, it worked very simple.

1. edit `package.json`
2. run `yarn`
3. `yarn.lock` is updated

### CODE REVIEW

**Comment by abouthiroppy** [comment]
Why do we need to change to yarn?

**Comment by okonomi** [comment]
@abouthiroppy Sorry, I made this PR without description.
I will add it soon.

**Comment by okonomi** [comment]
@abouthiroppy Added description.

**Comment by abouthiroppy** [comment]
I'm -1 on this changes. We can use `package-lock.json` of npm5. /cc @sotarok @suzuki

**Comment by abouthiroppy** [comment]
related https://github.com/crowi/crowi/pull/267

**Comment by okonomi** [comment]
@abouthiroppy I missed that PR!
Probably, any problems will be solved without switching to "YARN" when upgrade to npm@5.

**Pull request closed without merging**
