### PR TITLE
Implement "Notification"

### LINKED ISSUE #127: Notifications
I think that it will be great if there are some notifications triggered by user actions.

For instance:
- User creates/edits article
- User writes comment
- User likes article

I sometimes missed important comments or modifications on my article or other articles which I `Liked`.
I wanted to let me know when someone writes comment or edits article so that I respond to it as soon as possible.
For the sake of personal preference, it will be good that notifications can be turned on/off privately.

### PR DESCRIPTION
**Pull request by suzuki**
# Implement "Notifications"

## About

- In-App notification
    - When one user comment to page, notify other users
- Notify target users
    - creator and editor that page
    - commenter that page
- resolve #127

### Models

- Created new Models
    - Activity
    - Notification
    - NotificationStatus

### Flow

notification

### Comment

- When User_a post comment to page created by user_b.
    - User_b got a notification.

## **Not supported** this pull request

- Notification by Like
- Remote notification (such as Slack)
- Infinity scroll in notification view

## Want to discuss

- Notification page path
    - In this p-r, I used `/me/notifications` 
        - Is this selection ok?

### CODE REVIEW

**Comment by sotarok** [comment]
Thank you for the great PR, I'll check it soon.

**Comment by sotarok** [comment]
あとテストがこける ... (validation not work とかいって

**Comment by suzuki** [comment]
I will modify view of "zero notification" in this p-r.

**Comment by suzuki** [comment]
Added null message.

**Comment by abouthiroppy** [comment]
Is this active?

**Comment by sotarok** [comment]
yes, i'll still working on it.
but, i found that the issue of the design for this implementation.
i haven't found the way to resolve it yet (so it would take a wille ...)

**Comment by sotarok** [comment]
Will be implemented in v1.8

#367
#343

**Pull request closed without merging**
