### PR TITLE
Render HTML from JSX on the server

### PR DESCRIPTION
**Pull request by lightnet328**
# WHAT

- Render HTML from JSX on the server using express-react-views

# WHY

- To make migrating to SPA easier
  - I think it's easier to using SSR after rewriting Swig to JSX than changing Swig to a React component at once

This PR depends on #634

### CODE REVIEW

**Comment by saitoeku3** [comment]
`client/util` still exists after 'Rename to utils'.
Screen Shot 2020-03-02 at 22 24 08

**Comment by saitoeku3** [comment]
when I open Storybook,  it is crashed because `APP_CONTEXT` is missing.

Screen Shot 2020-03-02 at 22 52 04

```
TypeError: Cannot read property 'user' of undefined
    at Object.lookup (http://localhost:6001/main.7ded10f007708373fdce.bundle.js:14183:33)
    at http://localhost:6001/vendors~main.7ded10f007708373fdce.bundle.js:192452:54
    at Array.forEach ()
    at Browser.detect (http://localhost:6001/vendors~main.7ded10f007708373fdce.bundle.js:192450:22)
    at I18n.changeLanguage (http://localhost:6001/vendors~main.7ded10f007708373fdce.bundle.js:194608:47)
    at load (http://localhost:6001/vendors~main.7ded10f007708373fdce.bundle.js:194460:16)
    at I18n.init (http://localhost:6001/vendors~main.7ded10f007708373fdce.bundle.js:194474:9)
    at http://localhost:6001/main.7ded10f007708373fdce.bundle.js:14187:136
    at Module../client/components/Admin/AdminPage.stories.tsx (http://localhost:6001/main.7ded10f007708373fdce.bundle.js:94:54)
    at __webpack_require__ (http://localhost:6001/runtime~main.7ded10f007708373fdce.bundle.js:786:30)
```

**Comment by lightnet328** [comment]
I created `utils` directory. But I should have to keep its name.
However, It is difficult to revert these changes at the moment because they will be conflicted with other branches. So I'll revert its name after other branches merged.
Anyway, I changed `util` directory name to `utils`.
https://github.com/crowi/crowi/pull/639#issuecomment-593399996

**Comment by lightnet328** [comment]
For temporary solution, I assigned `window.APP_CONTEXT` when `createAppContext` function called.
https://github.com/crowi/crowi/pull/639#issuecomment-593413355

**Pull request merged**
